FROM debian:latest as base

RUN apt update -y
RUN apt upgrade -y
RUN apt install python3-pip -y

WORKDIR /tmp/build
COPY ./requirements.txt ./requirements.txt

RUN pip install flask opencv-python opencv-python-headless vidgear[core] grpcio grpcio-tools --break-system-packages

RUN rm -rf /tmp/build

RUN apt-get install ffmpeg libsm6 libxext6 -y

FROM base

WORKDIR /opt/videotracking-grpc
COPY . .

EXPOSE 8080/tcp

CMD python3 WebServer.py