# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yolo.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nyolo.proto\x12\x04Yolo\"\'\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\x12\x10\n\x08metadata\x18\x02 \x01(\x0c\x32M\n\x04Yolo\x12\"\n\x06\x44\x65tect\x12\x0b.Yolo.Image\x1a\x0b.Yolo.Image\x12!\n\x05Track\x12\x0b.Yolo.Image\x1a\x0b.Yolo.Image')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGE']._serialized_start=20
  _globals['_IMAGE']._serialized_end=59
  _globals['_YOLO']._serialized_start=61
  _globals['_YOLO']._serialized_end=138
# @@protoc_insertion_point(module_scope)
